services:
  broker:
    build: ./broker
    container_name: broker
    command: ["python", "broker.py"]

  server_python:
   build: ./python
   container_name: server_python
   command: ["python", "server.py"]
   environment:
     SERVER_ID: server_python
     DB_PATH: /app/data/server_python.db
     PUB_PORT: "7000"
     PEER_PUBS: tcp://server_java:7001,tcp://server_c:7002
   volumes:
     - ./data/python:/app/data
   depends_on:
     - broker

  
#  server_java:
#    build: ./java
#    container_name: server_java
#    environment:
#      ROLE: server
#      SERVER_ID: server_java
#      DB_PATH: /app/data/server_java.db
#      PUB_PORT: "7001"
#      PEER_PUBS: tcp://server_python:7000,tcp://server_c:7002
#    volumes:
#      - ./data/java:/app/data
#    depends_on:
#      - broker

  

  client_python:
    build: ./python
    container_name: client_python
    command: ["python", "client.py"]
    environment:
      CLIENT_USER: bot_python
      START_DELAY: "6"
      CHANNEL_TO_CREATE: geral
    depends_on:
      - broker
      - server_python
    #  - server_java
     # - server_c

  # client_java:
  #   build: ./java
  #   container_name: client_java
  #   environment:
  #     ROLE: client
  #     CLIENT_USER: bot_java
  #     START_DELAY: "9"
  #     CHANNEL_TO_CREATE: java_room
  #   depends_on:
  #     - broker
  #     - server_python
  #     - server_java
  #     - server_c

  # client_c:
  #   build: ./c
  #   container_name: client_c
  #   environment:
  #     ROLE: client
  #     CLIENT_USER: bot_c
  #     START_DELAY: "12"
  #     CHANNEL_TO_CREATE: c_room
  #   depends_on:
  #     - broker
  #     - server_python
  #     - server_java
  #     - server_c
